# Generated by Django 3.2 on 2022-06-28 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='ASN-2022-06-28', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('shipping_cost', models.BigIntegerField(default=0)),
                ('other_cost', models.BigIntegerField(default=0, help_text='Record other related costs here such as onboarding costs.')),
                ('est_shipping_date', models.DateField(blank=True, null=True)),
                ('act_shipping_date', models.DateField(blank=True, null=True)),
                ('est_receiving_date', models.DateField(blank=True, null=True)),
                ('act_receiving_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Make sure information in this transaction is correct. Once is_complete is checked, it cannot be unchecked.')),
                ('receiver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_receiver', to='contactapp.location')),
                ('sender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_sender', to='contactapp.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='ASN-2022-06-28', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('quantity_received', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionsapp.asn')),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.item')),
            ],
        ),
    ]
