# Generated by Django 3.2.3 on 2021-08-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_number', models.CharField(max_length=100)),
                ('est_shipping_date', models.DateField(blank=True, null=True)),
                ('act_shipping_date', models.DateField(blank=True, null=True)),
                ('est_receiving_date', models.DateField(blank=True, null=True)),
                ('act_receiving_date', models.DateField(blank=True, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=4, help_text='Shipping and handling costs associated with this ASN', max_digits=14, null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='\n            Make sure information in this ASN is correct. Once checked is_complete, \n            cannot be unchecked.')),
                ('ship_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_from_asn', to='contactapp.supplier')),
                ('ship_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_asn', to='contactapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contactapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='transactionsapp.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='itemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='StaticField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_fields', to='transactionsapp.order')),
                ('order_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_fields', to='transactionsapp.orderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('asns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_asns', to='transactionsapp.asn')),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_parts', to='itemsapp.part')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, help_text='Divides by this number. 1 box if used by box, or 24 pcs per box if used by piece', null=True)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_parts', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_products', to='itemsapp.product')),
                ('suppliers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_suppliers', to='contactapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ASNDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.IntegerField(blank=True, help_text='Quantity shipped.', null=True)),
                ('quantity_received', models.IntegerField(blank=True, help_text='Quantity received.', null=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ASNdetails', to='transactionsapp.asn')),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parts_ASNdetails', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products_ASNdetails', to='itemsapp.product')),
            ],
        ),
    ]
