# Generated by Django 3.2 on 2022-02-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='digital_products',
        ),
    ]
