# Generated by Django 3.2.3 on 2021-08-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0001_initial'),
        ('transactionsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.IntegerField(blank=True, help_text='Quantity shipped.', null=True)),
                ('quantity_received', models.IntegerField(blank=True, help_text='Quantity received.', null=True)),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parts_TransactionDetails', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products_TransactionDetails', to='itemsapp.product')),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='asns',
            new_name='transactions',
        ),
        migrations.RenameModel(
            old_name='ASN',
            new_name='Transaction',
        ),
        migrations.DeleteModel(
            name='ASNDetails',
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransactionDetails', to='transactionsapp.transaction'),
        ),
    ]
