# Generated by Django 3.2 on 2022-02-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ship_from_location',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ship_from_supplier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ship_to_location',
        ),
    ]
