# Generated by Django 3.2 on 2022-02-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0002_remove_bid_digital_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
