# Generated by Django 3.2.3 on 2021-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0002_auto_20210824_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactionsapp.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('ASN', 'Advanced Shipping Notice'), ('TRS', 'Transfer'), ('ADJ', 'Inventory Adjustment'), ('ORD', 'Order'), ('RET', 'Return')], max_length=3),
        ),
    ]
