# Generated by Django 3.2 on 2022-02-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0002_auto_20220225_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='products',
        ),
    ]
