# Generated by Django 3.2 on 2022-04-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0002_auto_20220401_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='number',
            field=models.CharField(default='ASN-2022-04-03', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='number',
            field=models.CharField(default='ASN-2022-04-03', max_length=100),
        ),
    ]
