# Generated by Django 3.2 on 2022-02-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0003_delete_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
