# Generated by Django 3.2.3 on 2021-08-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0003_auto_20210824_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='asn_number',
            new_name='transaction_number',
        ),
    ]
