# Generated by Django 3.2 on 2022-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0003_auto_20220403_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='number',
            field=models.CharField(default='ASN-2022-04-04', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='number',
            field=models.CharField(default='ASN-2022-04-04', max_length=100),
        ),
    ]
