# Generated by Django 3.2 on 2022-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0003_auto_20220225_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASN',
        ),
        migrations.DeleteModel(
            name='InvAdjustment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='act_receiving_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='act_shipping_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='est_receiving_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='est_shipping_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipping',
            field=models.BigIntegerField(default=0, help_text='Shipping and handling costs associated with this transaction'),
        ),
    ]
