# Generated by Django 3.2 on 2022-02-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_auto_20220213_1004'),
        ('transactionsapp', '0004_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Transaction',
            name='ship_from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_from_location', to='contactapp.location'),
        ),
        migrations.AlterField(
            model_name='Transaction',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_location', to='contactapp.location'),
        ),
    ]
