# Generated by Django 3.2.3 on 2021-09-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_alter_productpartjoin_quantity'),
        ('transactionsapp', '0004_rename_asn_number_transaction_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='staticfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='staticfield',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='note',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_products', to='itemsapp.product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='StaticField',
        ),
    ]
