# Generated by Django 3.2 on 2022-03-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0004_auto_20220301_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
