# Generated by Django 3.2 on 2022-03-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemsapp', '0030_auto_20220301_1602'),
        ('configapp', '0059_alter_profile_cdn_dir'),
        ('transactionsapp', '0005_auto_20220301_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('shipping_cost', models.BigIntegerField(default=0)),
                ('onboarding_cost', models.BigIntegerField(default=0)),
                ('est_shipping_date', models.DateField(blank=True, null=True)),
                ('act_shipping_date', models.DateField(blank=True, null=True)),
                ('est_receiving_date', models.DateField(blank=True, null=True)),
                ('act_receiving_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Make sure information in this transaction is correct. Once is_complete is checked, it cannot be unchecked.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.store')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.supplier')),
                ('warehouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.component')),
                ('part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='AsnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('quantity_received', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionsapp.asn')),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionsapp.item')),
            ],
        ),
        migrations.AddField(
            model_name='asn',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_receiver', to='transactionsapp.location'),
        ),
        migrations.AddField(
            model_name='asn',
            name='sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_sender', to='transactionsapp.location'),
        ),
    ]
