# Generated by Django 3.2.3 on 2021-09-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
        ('transactionsapp', '0006_invadjustment_order_return_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ship_from',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ship_from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_from_location', to='contactapp.location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ship_from_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_from_supplier', to='contactapp.supplier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='\n            Make sure information in this transaction is correct. \n            Once is_complete is checked, it cannot be unchecked.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_location', to='contactapp.location'),
        ),
    ]
