# Generated by Django 3.2 on 2022-03-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asn',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='asn',
            name='sender',
        ),
    ]
