# Generated by Django 3.2 on 2022-03-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0007_auto_20220301_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='receiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_receiver', to='transactionsapp.location'),
        ),
        migrations.AddField(
            model_name='asn',
            name='sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asn_sender', to='transactionsapp.location'),
        ),
    ]
