# Generated by Django 3.2.3 on 2021-09-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0007_auto_20210922_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ship_to',
            new_name='ship_to_location',
        ),
    ]
