# Generated by Django 3.2.3 on 2021-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0008_rename_ship_to_transaction_ship_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Shipping and handling costs associated with this transaction', max_digits=14, null=True),
        ),
    ]
