# Generated by Django 3.2 on 2022-03-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0008_auto_20220301_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='store',
        ),
        migrations.RemoveField(
            model_name='location',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='location',
            name='warehouse',
        ),
    ]
