# Generated by Django 3.2 on 2022-03-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0009_auto_20220302_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asn',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='asn',
            name='sender',
        ),
    ]
