# Generated by Django 3.2.3 on 2021-10-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0023_auto_20211012_1356'),
        ('transactionsapp', '0009_alter_transaction_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bundle_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_bundle_products', to='itemsapp.bundleproduct'),
        ),
        migrations.AddField(
            model_name='bid',
            name='digital_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_digital_products', to='itemsapp.digitalproduct'),
        ),
        migrations.AddField(
            model_name='bid',
            name='simple_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_simple_products', to='itemsapp.simpleproduct'),
        ),
        migrations.AddField(
            model_name='bid',
            name='variable_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_variable_products', to='itemsapp.variableproduct'),
        ),
    ]
