# Generated by Django 3.2 on 2022-03-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0012_auto_20220302_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='component',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
    ]
