# Generated by Django 3.2 on 2022-03-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0014_auto_20220303_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
