# Generated by Django 3.2 on 2022-03-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0040_item_price'),
        ('transactionsapp', '0015_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetails',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.item'),
        ),
    ]
