# Generated by Django 3.2 on 2022-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0016_asndetails_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='number',
            field=models.CharField(default='ASN-2022-03-04', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='number',
            field=models.CharField(default='ASN-2022-03-04', max_length=100),
        ),
    ]
