# Generated by Django 3.2 on 2022-12-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cdn_dir',
        ),
    ]
