# Generated by Django 3.2.3 on 2021-12-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_lg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_md',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_sm',
        ),
        migrations.AlterField(
            model_name='assett',
            name='img_1x1',
            field=models.ImageField(blank=True, help_text='recommended size: 250px x 250px', null=True, upload_to='advertisingapp/assetts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_skyscraper',
            field=models.ImageField(blank=True, help_text='recommended size: 160px x 600px', null=True, upload_to='advertisingapp/banners/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_xl',
            field=models.ImageField(blank=True, help_text='recommended size: 1140px x 380px', null=True, upload_to='advertisingapp/banners/%Y/%m/%d/'),
        ),
    ]
