# Generated by Django 3.2 on 2022-04-01 20:06

import configapp.utils.images
from django.db import migrations, models
import sodavault.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='ban_inline_rectangle',
            field=models.ImageField(blank=True, help_text='recommended size: 300px x 250px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ban_leaderboard',
            field=models.ImageField(blank=True, help_text='recommended size: 728px x 90px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ban_lg_leaderboard',
            field=models.ImageField(blank=True, help_text='recommended size: 970px x 90px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ban_lg_rectangle',
            field=models.ImageField(blank=True, help_text='recommended size: 336px x 280px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ban_skyscraper',
            field=models.ImageField(blank=True, help_text='recommended size: 160px x 600px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ban_square',
            field=models.ImageField(blank=True, help_text='recommended size: 500px x 500px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
    ]
