# Generated by Django 3.2 on 2022-04-03 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisingapp', '0002_auto_20220401_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisingapp_user_banner', to=settings.AUTH_USER_MODEL),
        ),
    ]
