# Generated by Django 3.2.3 on 2021-12-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0002_auto_20211217_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_lg',
            field=models.ImageField(blank=True, help_text='automatic size: 960px x 320px', null=True, upload_to='advertisingapp/banners/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_md',
            field=models.ImageField(blank=True, help_text='automatic size: 720px x 240px', null=True, upload_to='advertisingapp/banners/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_sm',
            field=models.ImageField(blank=True, help_text='automatic size: 540px x 180px', null=True, upload_to='advertisingapp/banners/%Y/%m/%d/'),
        ),
    ]
