# Generated by Django 3.2.3 on 2021-12-20 17:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0003_auto_20211219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_skyscraper',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='recommended size: 160px x 600px', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_xl',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='recommended size: 1140px x 380px', null=True, upload_to='avatars'),
        ),
    ]
