# Generated by Django 3.2 on 2022-04-03 08:18

import configapp.utils.images
from django.db import migrations, models
import sodavault.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0003_banner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ban_square',
            new_name='lg_11',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_lg_leaderboard',
            new_name='lg_leaderboard',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_md_square',
            new_name='md_11',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_lg_rectangle',
            new_name='md_rectangle',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_skyscraper',
            new_name='skyscraper',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_sm_square',
            new_name='sm_11',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_leaderboard',
            new_name='sm_leaderboard',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ban_inline_rectangle',
            new_name='sm_rectangle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ban_lg_square',
        ),
        migrations.AddField(
            model_name='banner',
            name='md_leaderboard',
            field=models.ImageField(blank=True, help_text='recommended size: 790px x 90px', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
    ]
