# Generated by Django 3.2 on 2022-04-03 11:45

import configapp.utils.images
from django.db import migrations, models
import sodavault.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0004_auto_20220403_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='lg_11',
            field=models.ImageField(blank=True, help_text='Recommended size: 500px x 500px Recommended name: name-11.jpg', null=True, storage=sodavault.custom_storage.MediaStorage(), upload_to=configapp.utils.images.user_file_path),
        ),
    ]
