# Generated by Django 3.2.3 on 2021-12-24 20:48

import advertisingapp.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0008_auto_20211224_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='assett',
            name='img_1x1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='recommended size: 250px x 250px', null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_skyscraper',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='recommended size: 160px x 600px', null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_xl',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='recommended size: 1140px x 380px', null=True, upload_to=""),
        ),
    ]
