# Generated by Django 3.2.3 on 2021-12-25 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisingapp', '0011_auto_20211225_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='400 characters max', max_length=400, null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_link',
            field=models.URLField(blank=True, help_text="End url with '/'", max_length=100, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_name',
            field=models.CharField(blank=True, help_text='URL tool tip on mouse hover.', max_length=70, verbose_name='URL Name'),
        ),
        migrations.DeleteModel(
            name='Assett',
        ),
    ]
