# Generated by Django 3.2 on 2022-02-06 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemsapp', '0001_initial'),
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(default=datetime.date.today)),
                ('expires', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(default=datetime.date.today)),
                ('expires', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(choices=[('APAY', 'Accounts Payable'), ('COGM', 'Cost of Goods Manufactured'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('IRAW', 'Inventory Raw Materials'), ('IMER', 'Inventory Merchandise'), ('ILOS', 'Inventory Loss'), ('OWEQ', 'Owner Equity')], max_length=4)),
                ('date', models.DateField(default=datetime.date.today)),
                ('debit_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('credit_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('batches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_batches', to='ledgerapp.batch')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_locations', to='contactapp.location')),
                ('lots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_lots', to='ledgerapp.lot')),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_parts', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_products', to='itemsapp.product')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
