# Generated by Django 3.2.3 on 2021-08-23 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(default=datetime.date.today)),
                ('expires', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('APAY', 'Accounts Payable'), ('INVN', 'Inventory'), ('ILOS', 'Inventory Loss'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('OWEQ', 'Owner Equity')], max_length=4)),
                ('date', models.DateField(default=datetime.date.today)),
                ('debit_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('credit_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact_locations', to='contactapp.location')),
                ('lots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact_lots', to='ledgerapp.lot')),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact_parts', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact_products', to='itemsapp.product')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
