# Generated by Django 3.2 on 2022-02-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='store',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='warehouse',
        ),
    ]
