# Generated by Django 3.2.3 on 2021-09-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0002_auto_20210901_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.CharField(choices=[('APAY', 'Accounts Payable'), ('INVN', 'Inventory'), ('ILOS', 'Inventory Loss'), ('COGM', 'Cost of Goods Manufactured'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('OWEQ', 'Owner Equity')], max_length=4),
        ),
    ]
