# Generated by Django 3.2 on 2022-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0002_auto_20220213_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-42d2090a-b642-4950-86c0', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-5ea0e081-b5f2-4572-84cf', max_length=100, unique=True),
        ),
    ]
