# Generated by Django 3.2 on 2022-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0002_auto_20220225_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='created_date',
            new_name='timestamp_created',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='modified_date',
            new_name='timestamp_modified',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='created_date',
            new_name='timestamp_created',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='modified_date',
            new_name='timestamp_modified',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='created_date',
            new_name='timestamp_created',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='modified_date',
            new_name='timestamp_modified',
        ),
    ]
