# Generated by Django 3.2.3 on 2021-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0003_alter_entry_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.CharField(choices=[('APAY', 'Accounts Payable'), ('IRAW', 'Inventory Raw Materials'), ('IFGD', 'Inventory Finished Goods'), ('IMER', 'Inventory Merchandise'), ('ILOS', 'Inventory Loss'), ('COGM', 'Cost of Goods Manufactured'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('OWEQ', 'Owner Equity')], max_length=4),
        ),
    ]
