# Generated by Django 3.2 on 2022-02-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0003_auto_20220225_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='part',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
    ]
