# Generated by Django 3.2 on 2022-02-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_company_domain'),
        ('ledgerapp', '0003_auto_20220213_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-257fded5-dec1-48aa-9b1f', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactapp.location'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-92e9c45a-8c9d-4128-b624', max_length=100, unique=True),
        ),
    ]
