# Generated by Django 3.2.3 on 2021-09-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0005_auto_20210907_0456'),
        ('ledgerapp', '0004_auto_20210909_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='batches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_batches', to='ledgerapp.batch'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_locations', to='contactapp.location'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_lots', to='ledgerapp.lot'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_parts', to='itemsapp.part'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_products', to='itemsapp.product'),
        ),
    ]
