# Generated by Django 3.2 on 2022-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0004_auto_20220225_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
