# Generated by Django 3.2.3 on 2021-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0005_auto_20210909_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.CharField(choices=[('APAY', 'Accounts Payable'), ('COGM', 'Cost of Goods Manufactured'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('IRAW', 'Inventory Raw Materials'), ('IMER', 'Inventory Merchandise'), ('ILOS', 'Inventory Loss'), ('OWEQ', 'Owner Equity')], max_length=4),
        ),
    ]
