# Generated by Django 3.2 on 2022-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0005_auto_20220213_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-7fc73fe4-06bd-4d78-b6cc', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-2eab7c24-5f52-410c-bfbf', max_length=100, unique=True),
        ),
    ]
