# Generated by Django 3.2 on 2022-03-03 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0023_auto_20220302_1138'),
        ('itemsapp', '0041_auto_20220303_1555'),
        ('ledgerapp', '0005_auto_20220303_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_item', to='itemsapp.item'),
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='le_location', to='contactapp.location'),
        ),
#         migrations.AlterField(
            # model_name='entry',
            # name='lot',
            # field=models.DateField(default=django.utils.timezone.now),
        # ),
    ]
