# Generated by Django 3.2 on 2022-02-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20220213_1004'),
        ('ledgerapp', '0006_auto_20220213_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='location',
        ),
        migrations.AddField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companies', to='contactapp.company'),
        ),
        migrations.AddField(
            model_name='entry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_store', to='contactapp.store'),
        ),
        migrations.AddField(
            model_name='entry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_warehouse', to='contactapp.warehouse'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-c89848ba-dcf5-4b39-bd26', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-6b967555-3bdc-46f5-8838', max_length=100, unique=True),
        ),
    ]
