# Generated by Django 3.2 on 2022-03-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0006_auto_20220303_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='lot',
        ),
    ]
