# Generated by Django 3.2.3 on 2021-09-15 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0006_alter_entry_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
