# Generated by Django 3.2 on 2022-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0007_auto_20220213_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-2203a665-9950-49c1-a169', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-69c49eca-d6e9-4c01-951e', max_length=100, unique=True),
        ),
    ]
