# Generated by Django 3.2 on 2022-03-03 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0007_remove_entry_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='lot',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
