# Generated by Django 3.2 on 2022-03-03 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0008_entry_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lot',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
