# Generated by Django 3.2 on 2022-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0009_alter_entry_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.AlterField(
            model_name='entry',
            name='credit_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='credit_quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit_quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
