# Generated by Django 3.2 on 2022-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0009_auto_20220213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-e992437c-0c9c-46f2-a5b4', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-dbb36bec-687b-484c-a4fe', max_length=100, unique=True),
        ),
    ]
