# Generated by Django 3.2 on 2022-03-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0010_auto_20220304_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='item',
        ),
    ]
