# Generated by Django 3.2 on 2022-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0010_auto_20220213_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-911ec939-086b-4ed1-b8bb', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-1c38e771-f321-4808-8228', max_length=100, unique=True),
        ),
    ]
