# Generated by Django 3.2 on 2022-03-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0011_remove_entry_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
