# Generated by Django 3.2 on 2022-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0011_auto_20220213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identification',
            field=models.CharField(default='BATCH-293f0c55-7acc-4eb4-9b52', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='identification',
            field=models.CharField(default='LOT-26e96a79-88e3-437a-9685', max_length=100, unique=True),
        ),
    ]
