# Generated by Django 3.2 on 2022-02-25 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('iso_code', models.CharField(blank=True, max_length=50)),
                ('fractional_unit', models.CharField(blank=True, max_length=50)),
                ('number_basic', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('INV', 'Inventory Stock'), ('DIS', 'Display')], max_length=3)),
                ('singular', models.CharField(default='piece', max_length=100)),
                ('plural', models.CharField(default='pieces', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Recommended size 250 x 250px', null=True, upload_to='configapp/avatars/%Y/%m/%d')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cdn_dir', models.CharField(default='450573f9-73cd', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create_users', 'Can create new users.'), ('view_token', 'Can view token.'), ('change_token', 'Can change token.')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('symbol_location', models.CharField(blank=True, max_length=200)),
                ('is_space_separation', models.BooleanField(default=True, help_text='Provides a space between the currency symbol and price.')),
                ('fractional_separator', models.CharField(blank=True, choices=[('DEC', '.'), ('COM', ',')], max_length=3)),
                ('thousands_separator', models.CharField(blank=True, choices=[('DEC', '.'), ('COM', ',')], max_length=3)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
