# Generated by Django 3.2 on 2022-02-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
