# Generated by Django 3.2 on 2022-03-31 15:59

import configapp.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lg_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 1200px x 630px Recommended name: name-191.jpg', null=True, storage=configapp.utils.images.OverwriteStorage(), upload_to=configapp.utils.images.new_filename),
        ),
        migrations.AlterField(
            model_name='image',
            name='lg_21',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200px x 600px. Recommended name: name-21.jpg', null=True, storage=configapp.utils.images.OverwriteStorage(), upload_to=configapp.utils.images.new_filename),
        ),
    ]
