# Generated by Django 3.2 on 2022-02-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cat_type', models.CharField(blank=True, choices=[('CAT', 'Category'), ('TAG', 'Tag'), ('DEP', 'Department'), ('ATT', 'Attribute')], max_length=3)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_secondary', models.BooleanField(default=False)),
                ('is_tertiary', models.BooleanField(default=False)),
                ('order', models.CharField(blank=True, max_length=20)),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
