# Generated by Django 3.2 on 2021-12-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_profile_pen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('create_users', 'Can create new users.'), ('view_token', 'Can view token.'), ('change_token', 'Can change token.')]},
        ),
    ]
