# Generated by Django 3.2 on 2022-09-07 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_apicredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='prefix',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
