# Generated by Django 3.2 on 2022-02-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
