# Generated by Django 3.2 on 2021-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended size 250 x 250px', null=True, upload_to='configapp/avatars/%Y/%m/%d'),
        ),
    ]
