# Generated by Django 3.2 on 2022-02-10 11:16

from django.db import migrations, models
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0006_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': '05. Groups'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='cat_type',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('BLOGCAT', 'Blog Category'), ('BLOGTAG', 'Blog Tag'), ('ITEMCAT', 'Item Category'), ('ITEMTAG', 'Item Tag'), ('ITEMDEP', 'Item Department'), ('ITEMATT', 'Item Attribute')], max_length=7),
        ),
        migrations.AddField(
            model_name='group',
            name='image_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 1200px x 630px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
        migrations.AddField(
            model_name='group',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
        migrations.AddField(
            model_name='group',
            name='image_lg_square',
            field=models.CharField(blank=True, help_text='Automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='image_md_square',
            field=models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='image_sm_square',
            field=models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='image_thumb',
            field=models.ImageField(blank=True, help_text='Recommended size 500px x 500px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
        migrations.AddField(
            model_name='group',
            name='kwd_list',
            field=models.CharField(blank=True, help_text='Comma-separated values.', max_length=100, verbose_name='Category Keywords'),
        ),
        migrations.AddField(
            model_name='group',
            name='locations',
            field=models.ManyToManyField(blank=True, to='configapp.Location'),
        ),
    ]
