# Generated by Django 3.2 on 2022-09-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0007_apicredentials_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
