# Generated by Django 3.2 on 2022-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0008_alter_profile_cdn_dir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppier',
            new_name='Supplier',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='15a406ab-86b7', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
