# Generated by Django 3.2 on 2022-02-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0008_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='kwd_list',
            field=models.CharField(blank=True, help_text='Comma-separated values.', max_length=100),
        ),
    ]
