# Generated by Django 3.2 on 2022-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_post_locations'),
        ('ledgerapp', '0004_auto_20220213_0935'),
        ('contactapp', '0003_company_domain'),
        ('configapp', '0011_currency_currencyconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='group',
            name='locations',
            field=models.ManyToManyField(blank=True, to='contactapp.Location'),
        ),
    ]
