# Generated by Django 3.2 on 2022-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_auto_20220213_1004'),
        ('configapp', '0012_auto_20220213_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Group',
            name='locations',
            field=models.ManyToManyField(blank=True, to='contactapp.Location'),
        ),
    ]
