# Generated by Django 3.2 on 2022-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0012_auto_20220225_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='created_date',
            new_name='timestamp_created',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='modified_date',
            new_name='timestamp_modified',
        ),
        migrations.RenameField(
            model_name='currencyconfig',
            old_name='created_date',
            new_name='timestamp_created',
        ),
        migrations.RenameField(
            model_name='currencyconfig',
            old_name='modified_date',
            new_name='timestamp_modified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='43adf74b-7a4d', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
