# Generated by Django 3.2 on 2022-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20220213_1004'),
        ('configapp', '0013_alter_group_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='group_websites', to='contactapp.Website'),
        ),
        migrations.AlterField(
            model_name='group',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='group_locations', to='contactapp.Location'),
        ),
    ]
