# Generated by Django 3.2 on 2022-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20220213_1004'),
        ('configapp', '0014_auto_20220213_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='locations',
        ),
        migrations.AddField(
            model_name='group',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='group_companies', to='contactapp.Company'),
        ),
        migrations.AddField(
            model_name='group',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='group_stores', to='contactapp.Store'),
        ),
        migrations.AddField(
            model_name='group',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='group_warehouses', to='contactapp.Warehouse'),
        ),
    ]
