# Generated by Django 3.2 on 2022-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0016_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Is required and must be unique.', unique=True),
        ),
    ]
