# Generated by Django 3.2 on 2022-02-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0017_alter_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='configapp.group'),
        ),
    ]
