# Generated by Django 3.2 on 2022-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0018_auto_20220213_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
