# Generated by Django 3.2 on 2022-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0019_alter_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
