# Generated by Django 3.2 on 2022-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0020_alter_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('ITEMATT', 'Item Attribute'), ('ITEMCAT', 'Item Category'), ('ITEMDEP', 'Item Department'), ('ITEMTAG', 'Item Tag'), ('LOCACAT', 'Location Category'), ('LOCATAG', 'Location Tag'), ('POSTCAT', 'Post Category'), ('POSTTAG', 'Post Tag')], max_length=7),
        ),
    ]
