# Generated by Django 3.2 on 2022-02-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0021_alter_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='group',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='group',
            name='warehouses',
        ),
        migrations.RemoveField(
            model_name='group',
            name='websites',
        ),
    ]
