# Generated by Django 3.2 on 2022-02-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0022_auto_20220217_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('ITEMATT', 'Item Attribute'), ('ITEMCAT', 'Item Category'), ('ITEMDEP', 'Item Department'), ('ITEMTAG', 'Item Tag'), ('LOCACAT', 'Location Category'), ('LOCATAG', 'Location Tag'), ('ARTICAT', 'Article Category'), ('ARTITAG', 'Article Tag'), ('DOCSCAT', 'Docs Category'), ('DOCSTAG', 'Docs Tag'), ('PAGECAT', 'Page Category'), ('PAGETAG', 'Page Tag')], max_length=7),
        ),
    ]
