# Generated by Django 3.2 on 2022-02-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0024_alter_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_type',
        ),
    ]
