# Generated by Django 3.2 on 2022-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20220218_1557'),
        ('configapp', '0027_auto_20220218_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='websites',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
