# Generated by Django 3.2 on 2022-02-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0028_auto_20220218_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name_plural': 'Groupings'},
        ),
    ]
