# Generated by Django 3.2 on 2022-02-23 09:37

from django.db import migrations, models
from configapp.utils import utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0029_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_featured', models.ImageField(blank=True, help_text='Recommended size: 1200px x 600px', null=True, upload_to=utils_images.new_filename)),
                ('image_thumb', models.ImageField(blank=True, help_text='Recommended size: 500px x 500px', null=True, upload_to=utils_images.new_filename)),
                ('image_191', models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 1200px x 630px', null=True, upload_to=utils_images.new_filename)),
                ('image_title', models.CharField(blank=True, help_text='Alt text for image.', max_length=200, verbose_name='Image Title')),
                ('image_caption', models.CharField(blank=True, help_text='Caption for image.', max_length=200, verbose_name='Image Caption')),
                ('featured_lg', models.CharField(blank=True, help_text='Automatic size: 1200px x 600px', max_length=200)),
                ('featured_md', models.CharField(blank=True, help_text='Automatic size: 800px x 400px', max_length=200)),
                ('featured_sm', models.CharField(blank=True, help_text='Automatic size: 400px x 200px', max_length=200)),
                ('thumb_lg', models.CharField(blank=True, help_text='Automatic size: 500px x 500px', max_length=200)),
                ('thumb_md', models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200)),
                ('thumb_sm', models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image_dir',
            field=models.CharField(default='5ac7d6ee-7aa0', help_text='Root image dir. eg. https://cdn.sodavault.com/<image_dir>/Y/m/d/image.webp', max_length=20),
        ),
    ]
