# Generated by Django 3.2 on 2022-02-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0031_auto_20220227_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='4d92566b-c4d3', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
