# Generated by Django 3.2 on 2022-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0031_auto_20220223_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_dir',
        ),
        migrations.AddField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='9943c3df-63ae', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
