# Generated by Django 3.2 on 2022-02-23 15:07

import configapp.utils.utils_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0032_auto_20220223_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_thumb',
            new_name='image_11',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_featured',
            new_name='image_21',
        ),
        migrations.AddField(
            model_name='image',
            name='image_any',
            field=models.ImageField(blank=True, help_text='Image with custom size.', null=True, upload_to=configapp.utils.utils_images.new_filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='641ef134-cf7e', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
