# Generated by Django 3.2 on 2022-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0033_auto_20220227_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lg_11',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lg_191',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lg_21',
        ),
        migrations.RemoveField(
            model_name='image',
            name='md_11',
        ),
        migrations.RemoveField(
            model_name='image',
            name='md_21',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sm_11',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sm_21',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='59927a8b-1841', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
