# Generated by Django 3.2 on 2022-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0033_auto_20220223_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='thumb_lg',
            new_name='lg_11',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='featured_lg',
            new_name='lg_12',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='thumb_md',
            new_name='md_11',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='featured_md',
            new_name='md_12',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='thumb_sm',
            new_name='sm_11',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='featured_sm',
            new_name='sm_12',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='3cdf9e4f-354f', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
