# Generated by Django 3.2 on 2022-02-24 07:03

import configapp.utils.utils_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0034_auto_20220223_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='md_12',
            new_name='md_21',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='sm_12',
            new_name='sm_21',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lg_12',
        ),
        migrations.AddField(
            model_name='image',
            name='lg_21',
            field=models.CharField(blank=True, help_text='Automatic size: 2100px x 600px', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='image_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 2100px x 630px', null=True, upload_to=configapp.utils.utils_images.new_filename),
        ),
        migrations.AlterField(
            model_name='group',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 2100px x 600px', null=True, upload_to=configapp.utils.utils_images.new_filename),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 2100px x 630px', null=True, upload_to=configapp.utils.utils_images.new_filename),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size: 2100px x 600px', null=True, upload_to=configapp.utils.utils_images.new_filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='f3833303-3d2a', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
