# Generated by Django 3.2 on 2022-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0035_auto_20220224_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='lg_11',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lg_21',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='2352fe6e-a1af', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
