# Generated by Django 3.2 on 2022-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0036_auto_20220224_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_11',
            new_name='lg_11',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_191',
            new_name='lg_191',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_21',
            new_name='lg_21',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='eaa11423-5a17', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
