# Generated by Django 3.2 on 2022-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0014_auto_20220227_0924'),
        ('configapp', '0039_alter_profile_cdn_dir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='3182eebe-5205', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
