# Generated by Django 3.2 on 2022-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0064_auto_20220302_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('COMP', 'Company'), ('STOR', 'Store'), ('SUPP', 'Supplier'), ('WARE', 'Warehouse'), ('WEBS', 'Website')], max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='bb52d38c-0411', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
