# Generated by Django 3.2 on 2022-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0072_alter_profile_cdn_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.location',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cdn_dir',
            field=models.CharField(default='09a11d89-f581', help_text='User root cdn dir.eg. https://cdn.sodavault.com/image_dir/Y/m/d/image.webp', max_length=20),
        ),
    ]
