# Generated by Django 3.2.3 on 2021-08-23 17:30

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Category Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Category Description')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='resizes to 250 x 250px', null=True, upload_to='blog_images/category/%Y/%m/%d/')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Category Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Category Description')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tag Name')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('ARTICLE', 'Article'), ('PAGE', 'Page'), ('DOCS', 'Docs')], default='Article', max_length=20, verbose_name='Post Type')),
                ('menu_order', models.IntegerField(blank=True, help_text="Only required if post_type='Page'", null=True, verbose_name='Menu Order')),
                ('primary_menu', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('excerpt', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Max 200 characters.', max_length=200, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('status', models.CharField(blank=True, choices=[('PUBLI', 'Published'), ('DRAFT', 'Draft'), ('TRASH', 'Trash')], max_length=5, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, help_text='Moves post to front page.', verbose_name='Featured Post')),
                ('date_published', models.DateField(default=datetime.date.today, verbose_name='Date Published')),
                ('date_modified', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Modified')),
                ('keyword_list', models.CharField(blank=True, help_text='comma, separated, list', max_length=200, verbose_name='Keyword List')),
                ('featured_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='resizes to 800 x 400px', null=True, upload_to='blog_images/featured/%Y/%m/%d/')),
                ('thumbnail_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='resizes to 250 x 250px', null=True, upload_to='blog_images/thumbnail/%Y/%m/%d/')),
                ('image_title', models.CharField(blank=True, help_text='Alt text for image.', max_length=200, verbose_name='Image Title')),
                ('image_caption', models.CharField(blank=True, help_text='Caption for image.', max_length=200, verbose_name='Image Caption')),
                ('footer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use for footnotes, redactions and notes of changes or updates.', null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blogapp.Category')),
                ('locations', models.ManyToManyField(blank=True, related_name='posts', to='blogapp.Location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogapp.post')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blogapp.Tag')),
            ],
            options={
                'ordering': ('-featured', '-date_published'),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'date_published', 'post_type', 'featured'], name='blogapp_pos_status_6d0062_idx'),
        ),
    ]
