# Generated by Django 3.2 on 2022-02-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='post',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
