# Generated by Django 3.2.3 on 2021-10-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blogapp.post',),
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blogapp.post',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blogapp.post',),
        ),
        migrations.AddField(
            model_name='location',
            name='domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domain eg. example.com'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTI', 'Article'), ('PAGE', 'Page'), ('DOCS', 'Docs')], default='Article', max_length=20, verbose_name='Post Type'),
        ),
    ]
