# Generated by Django 3.2.3 on 2021-10-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20211011_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '01. Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '05. Categories'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name_plural': '02. Docs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '04. Locations'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': '03. Pages'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '06. Tags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='menu_order',
            field=models.IntegerField(blank=True, help_text='Use to order menu', null=True, verbose_name='Menu Order'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogapp.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTI', 'Article'), ('PAGE', 'Page'), ('DOCS', 'Docs')], default='ARTI', max_length=20, verbose_name='Post Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='primary_menu',
            field=models.BooleanField(default=False, help_text='Use if in primary menu.'),
        ),
    ]
