# Generated by Django 3.2 on 2022-02-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0006_location'),
        ('blogapp', '0002_auto_20220210_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='categories', to='configapp.Location'),
        ),
        migrations.AddField(
            model_name='post',
            name='locations',
            field=models.ManyToManyField(blank=True, to='configapp.Location'),
        ),
    ]
