# Generated by Django 3.2.3 on 2021-12-26 10:39

from django.db import migrations, models
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211011_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_lg_square',
            field=models.CharField(blank=True, help_text='automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='image_md_square',
            field=models.CharField(blank=True, help_text='automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='image_sm_square',
            field=models.CharField(blank=True, help_text='automatic size: 200px x 200px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_lg',
            field=models.CharField(blank=True, help_text='automatic size: 1600px x 800px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_md',
            field=models.CharField(blank=True, help_text='automatic size: 800px x 400px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_sm',
            field=models.CharField(blank=True, help_text='automatic size: 400px x 200px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_lg',
            field=models.CharField(blank=True, help_text='automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_md',
            field=models.CharField(blank=True, help_text='automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_sm',
            field=models.CharField(blank=True, help_text='automatic size: 200px x 200px', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='recommended size to 500px x 500px', null=True, upload_to=utilities.utils_images.new_filename_blog_cat),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1600 x 800px', null=True, upload_to=utilities.utils_images.new_filename_blog_feat),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 500 x 500px', null=True, upload_to=utilities.utils_images.new_filename_blog_thumb),
        ),
    ]
