# Generated by Django 3.2 on 2022-02-10 11:16

from django.db import migrations, models
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20220210_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size 500px x 500px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 1200px x 630px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_config_group),
        ),
    ]
