# Generated by Django 3.2 on 2022-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20220316_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('ARTICLE', 'Article'), ('DOCUMENTION', 'Documentation'), ('PAGE', 'Page')], max_length=11),
        ),
    ]
