# Generated by Django 3.2 on 2022-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20211226_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='primary_menu',
            new_name='is_primary_menu',
        ),
    ]
