# Generated by Django 3.2 on 2022-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_primary_menu_post_is_primary_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_footer_menu',
            field=models.BooleanField(default=False, help_text='Use if in footer menu.'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_secondary_menu',
            field=models.BooleanField(default=False, help_text='Use if in secondary menu.'),
        ),
    ]
