# Generated by Django 3.2 on 2022-02-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configapp', '0014_alter_profile_cdn_dir'),
        ('blogapp', '0005_auto_20220225_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.post')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='blogapp.Category')),
                ('parent', models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.page')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag')),
                ('websites', models.ManyToManyField(blank=True, to='configapp.Website')),
            ],
            bases=('blogapp.post',),
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.post')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='blogapp.Category')),
                ('parent', models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.doc')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag')),
                ('websites', models.ManyToManyField(blank=True, to='configapp.Website')),
            ],
            bases=('blogapp.post',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.post')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.book')),
                ('categories', models.ManyToManyField(blank=True, to='blogapp.Category')),
                ('local_business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.localbusiness')),
                ('movie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.movie')),
                ('parent', models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.article')),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.recipe')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag')),
                ('websites', models.ManyToManyField(blank=True, to='configapp.Website')),
            ],
            bases=('blogapp.post',),
        ),
    ]
