# Generated by Django 3.2 on 2022-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0007_auto_20220210_1116'),
        ('blogapp', '0006_auto_20220210_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
    ]
