# Generated by Django 3.2 on 2022-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20220113_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Use to order menu', verbose_name='Menu Order'),
        ),
    ]
