# Generated by Django 3.2 on 2022-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_article_doc_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.article'),
        ),
        migrations.AddField(
            model_name='image',
            name='doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.doc'),
        ),
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.page'),
        ),
    ]
