# Generated by Django 3.2 on 2022-02-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20220225_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
