# Generated by Django 3.2 on 2022-01-16 07:58

from django.db import migrations, models
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20220116_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image_featured',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_image',
            new_name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='post',
            name='keyword_list',
        ),
        migrations.AddField(
            model_name='post',
            name='image_191',
            field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 1200px x 630px', null=True, upload_to=utilities.utils_images.new_filename_blog_tag),
        ),
        migrations.AddField(
            model_name='post',
            name='image_21',
            field=models.ImageField(blank=True, help_text='recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_blog_tag),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, help_text='comma-separated list', max_length=200, verbose_name='Keyword List'),
        ),
    ]
