# Generated by Django 3.2 on 2022-02-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
