# Generated by Django 3.2 on 2022-01-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20220116_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keywords',
            new_name='kwd_list',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='keywords',
            new_name='kwd_list',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='keywords',
            new_name='kwd_list',
        ),
    ]
