# Generated by Django 3.2 on 2022-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20220116_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('page', 'Page'), ('doc', 'Docs')], default='ARTI', max_length=20, verbose_name='Post Type'),
        ),
    ]
