# Generated by Django 3.2 on 2022-02-27 08:58

import configapp.utils.utils_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20220227_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_ptr',
        ),
#         migrations.AddField(
            # model_name='image',
            # name='caption',
            # field=models.CharField(blank=True, help_text='Caption for image.', max_length=200),
        # ),
#         migrations.AddField(
            # model_name='image',
            # name='custom',
            # field=models.ImageField(blank=True, help_text='Image with custom size.', null=True, storage=configapp.utils.utils_images.OverwriteStorage(), upload_to=configapp.utils.utils_images.new_filename),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='id',
            # field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            # preserve_default=False,
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='lg_11',
            # field=models.ImageField(blank=True, help_text='Recommended size: 500px x 500px Recommended name: name-11.jpg', null=True, storage=configapp.utils.utils_images.OverwriteStorage(), upload_to=configapp.utils.utils_images.new_filename),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='lg_191',
            # field=models.ImageField(blank=True, help_text='1.9:1 ratio recommended size 2100px x 630px Recommended name: name-191.jpg', null=True, storage=configapp.utils.utils_images.OverwriteStorage(), upload_to=configapp.utils.utils_images.new_filename),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='lg_21',
            # field=models.ImageField(blank=True, help_text='Recommended size: 2100px x 600px. Recommended name: name-21.jpg', null=True, storage=configapp.utils.utils_images.OverwriteStorage(), upload_to=configapp.utils.utils_images.new_filename),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='md_11',
            # field=models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='md_21',
            # field=models.CharField(blank=True, help_text='Automatic size: 800px x 400px', max_length=200),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='sm_11',
            # field=models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='sm_21',
            # field=models.CharField(blank=True, help_text='Automatic size: 400px x 200px', max_length=200),
        # ),
        # migrations.AddField(
            # model_name='image',
            # name='title',
            # field=models.CharField(blank=True, help_text='Alt text for image.', max_length=200),
#         ),
    ]
