# Generated by Django 3.2 on 2022-01-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('page', 'Page'), ('doc', 'Docs')], default='article', max_length=20, verbose_name='Post Type'),
        ),
    ]
