# Generated by Django 3.2 on 2022-02-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_primary_menu',
            new_name='is_primary',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_secondary_menu',
            new_name='is_secondary',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_footer_menu',
            new_name='is_tertiary',
        ),
    ]
