# Generated by Django 3.2 on 2022-02-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20220227_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
