# Generated by Django 3.2 on 2022-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('PAGE', 'Page'), ('DOC', 'Docs')], default='article', max_length=20, verbose_name='Post Type'),
        ),
    ]
