# Generated by Django 3.2 on 2022-01-19 21:25

from django.db import migrations, models
import django.db.models.deletion
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_footer_menu',
            field=models.BooleanField(default=False, help_text='Use if in footer menu.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_primary_menu',
            field=models.BooleanField(default=False, help_text='Use if in primary menu.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_secondary_menu',
            field=models.BooleanField(default=False, help_text='Use if in secondary menu.'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Use to order menu', verbose_name='Menu Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogapp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='is_footer_menu',
            field=models.BooleanField(default=False, help_text='Use if in footer menu.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_primary_menu',
            field=models.BooleanField(default=False, help_text='Use if in primary menu.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_secondary_menu',
            field=models.BooleanField(default=False, help_text='Use if in secondary menu.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Use to order menu', verbose_name='Menu Order'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Self-referencing field to nest menus.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogapp.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size 500px x 500px', null=True, upload_to=utilities.utils_images.new_filename_blog_cat),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_blog_cat),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_lg_square',
            field=models.CharField(blank=True, help_text='Automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_md_square',
            field=models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_sm_square',
            field=models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_lg',
            field=models.CharField(blank=True, help_text='Automatic size: 1600px x 800px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_md',
            field=models.CharField(blank=True, help_text='Automatic size: 800px x 400px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_sm',
            field=models.CharField(blank=True, help_text='Automatic size: 400px x 200px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_blog_tag),
        ),
        migrations.AlterField(
            model_name='post',
            name='kwd_list',
            field=models.CharField(blank=True, help_text='Comma-separated list', max_length=200, verbose_name='Keyword List'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb_lg',
            field=models.CharField(blank=True, help_text='Automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb_md',
            field=models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb_sm',
            field=models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size 500px x 500px', null=True, upload_to=utilities.utils_images.new_filename_blog_tag),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_21',
            field=models.ImageField(blank=True, help_text='Recommended size 1200px x 600px', null=True, upload_to=utilities.utils_images.new_filename_blog_tag),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_lg_square',
            field=models.CharField(blank=True, help_text='Automatic size: 500px x 500px', max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_md_square',
            field=models.CharField(blank=True, help_text='Automatic size: 250px x 250px', max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_sm_square',
            field=models.CharField(blank=True, help_text='Automatic size: 200px x 200px', max_length=200),
        ),
    ]
