# Generated by Django 3.2 on 2022-02-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20220217_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name_plural': 'Docs'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
