# Generated by Django 3.2 on 2022-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0020_alter_group_order'),
        ('blogapp', '0014_auto_20220217_1012'),
    ]
