# Generated by Django 3.2 on 2022-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20220119_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blogapp.Location'),
        ),
        migrations.AddField(
            model_name='tag',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blogapp.Location'),
        ),
    ]
