# Generated by Django 3.2 on 2022-01-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20220121_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['menu_order', 'name'], 'verbose_name_plural': '05. Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['menu_order', 'name'], 'verbose_name_plural': '06. Tags'},
        ),
    ]
