# Generated by Django 3.2 on 2022-02-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0020_alter_group_order'),
        ('blogapp', '0015_auto_20220217_1607'),
    ]

    operations = [
        migrations.RenameModel('Category', 'PostCategory'),
        migrations.RenameModel('Tag', 'PostTag'),

        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='post_categories', to='blogapp.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='blogapp.PostTag'),
        ),
    ]
