# Generated by Django 3.2 on 2022-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_image_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='image',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
