# Generated by Django 3.2 on 2022-03-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20220301_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='websites',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='websites',
        ),
        migrations.RemoveField(
            model_name='page',
            name='websites',
        ),
    ]
