# Generated by Django 3.2 on 2022-02-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20220217_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
