# Generated by Django 3.2 on 2022-02-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20220217_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
