# Generated by Django 3.2 on 2022-01-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_ingredient_recipe_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='post',
        ),
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.recipe'),
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.review'),
        ),
    ]
