# Generated by Django 3.2 on 2022-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20220302_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='image',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('ARTI', 'Article'), ('DOCU', 'Documentation'), ('PAGE', 'Page')], max_length=4),
        ),
    ]
