# Generated by Django 3.2 on 2022-02-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0020_alter_group_order'),
        ('blogapp', '0018_auto_20220217_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
    ]
