# Generated by Django 3.2 on 2022-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20220122_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbusiness',
            name='url_map',
        ),
        migrations.RemoveField(
            model_name='reviewrestaurant',
            name='url_map',
        ),
        migrations.AddField(
            model_name='reviewbusiness',
            name='map_link',
            field=models.URLField(blank=True, help_text='Use google maps link.', max_length=100, verbose_name='Map link.'),
        ),
        migrations.AddField(
            model_name='reviewbusiness',
            name='website',
            field=models.URLField(blank=True, help_text='Use google maps link.', max_length=100, verbose_name='Business website.'),
        ),
        migrations.AddField(
            model_name='reviewrestaurant',
            name='map_link',
            field=models.URLField(blank=True, help_text='Use google maps link.', max_length=100, verbose_name='Map link.'),
        ),
        migrations.AddField(
            model_name='reviewrestaurant',
            name='website',
            field=models.URLField(blank=True, help_text='Use google maps link.', max_length=100, verbose_name='Business website.'),
        ),
    ]
