# Generated by Django 3.2 on 2022-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20220217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_posts', to='blogapp.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_posts', to='blogapp.PostTag'),
        ),
    ]
