# Generated by Django 3.2 on 2022-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20220122_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbusiness',
            name='business_website',
        ),
    ]
