# Generated by Django 3.2 on 2022-01-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_remove_reviewbusiness_business_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewbook',
            old_name='book_title',
            new_name='title',
        ),
    ]
