# Generated by Django 3.2 on 2022-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0027_auto_20220218_1334'),
        ('blogapp', '0021_auto_20220218_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='websites',
            field=models.ManyToManyField(blank=True, to='configapp.Website'),
        ),
    ]
