# Generated by Django 3.2 on 2022-01-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_rename_book_title_reviewbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbook',
            name='rating',
            field=models.CharField(blank=True, choices=[('10', '1.0 worst'), ('15', '1.5'), ('20', '2.0'), ('25', '2.5'), ('30', '3.0 average'), ('35', '3.5'), ('40', '4.0'), ('45', '4.5'), ('50', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewbusiness',
            name='rating',
            field=models.CharField(blank=True, choices=[('10', '1.0 worst'), ('15', '1.5'), ('20', '2.0'), ('25', '2.5'), ('30', '3.0 average'), ('35', '3.5'), ('40', '4.0'), ('45', '4.5'), ('50', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewmovie',
            name='rating',
            field=models.CharField(blank=True, choices=[('10', '1.0 worst'), ('15', '1.5'), ('20', '2.0'), ('25', '2.5'), ('30', '3.0 average'), ('35', '3.5'), ('40', '4.0'), ('45', '4.5'), ('50', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='rating',
            field=models.CharField(blank=True, choices=[('10', '1.0 worst'), ('15', '1.5'), ('20', '2.0'), ('25', '2.5'), ('30', '3.0 average'), ('35', '3.5'), ('40', '4.0'), ('45', '4.5'), ('50', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
    ]
