# Generated by Django 3.2 on 2022-03-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_alter_post_websites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name_plural': '__ categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug'], 'verbose_name_plural': '__ tags'},
        ),
    ]
