# Generated by Django 3.2 on 2022-02-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20220218_1557'),
    ]

#     operations = [
        # migrations.RemoveField(
            # model_name='post',
            # name='websites',
        # ),
        # migrations.DeleteModel(
            # name='Website',
        # ),
#     ]
