# Generated by Django 3.2 on 2022-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20220124_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbook',
            name='rating',
            field=models.CharField(blank=True, choices=[('1_0', '1.0 worst'), ('1_5', '1.5'), ('2_0', '2.0'), ('2_5', '2.5'), ('3_0', '3.0 average'), ('3_5', '3.5'), ('4_0', '4.0'), ('4_5', '4.5'), ('5_0', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewbusiness',
            name='rating',
            field=models.CharField(blank=True, choices=[('1_0', '1.0 worst'), ('1_5', '1.5'), ('2_0', '2.0'), ('2_5', '2.5'), ('3_0', '3.0 average'), ('3_5', '3.5'), ('4_0', '4.0'), ('4_5', '4.5'), ('5_0', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewmovie',
            name='rating',
            field=models.CharField(blank=True, choices=[('1_0', '1.0 worst'), ('1_5', '1.5'), ('2_0', '2.0'), ('2_5', '2.5'), ('3_0', '3.0 average'), ('3_5', '3.5'), ('4_0', '4.0'), ('4_5', '4.5'), ('5_0', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='rating',
            field=models.CharField(blank=True, choices=[('1_0', '1.0 worst'), ('1_5', '1.5'), ('2_0', '2.0'), ('2_5', '2.5'), ('3_0', '3.0 average'), ('3_5', '3.5'), ('4_0', '4.0'), ('4_5', '4.5'), ('5_0', '5.0 best')], help_text='5 stars is best.', max_length=3, verbose_name='Rating'),
        ),
    ]
