# Generated by Django 3.2 on 2022-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20220124_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, help_text='eg. Entree, Appetizer, Side.', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(blank=True, help_text='eg. Frying, Steaming, Baking.', max_length=50, verbose_name='Cooking method'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, help_text='eg. Italian, French, American.', max_length=50, verbose_name='Cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_calories',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Number of calories per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_carbs',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of carbohydrates per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_choles',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Milligrams of cholesterol per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_fat',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of fat per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_fiber',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of fiber per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_protein',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of protein per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_sat_fat',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of staurated fat per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_serving',
            field=models.CharField(blank=True, help_text='10 gram slice', max_length=50, verbose_name='Serving Size'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_sodium',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Milligrams of sodium per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_sugar',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of sugar per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_trans_fat',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of trans fat per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutr_unsat_fat',
            field=models.IntegerField(blank=True, help_text='100', null=True, verbose_name='Grams of unstaurated fat per serving.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='suitable',
            field=models.CharField(blank=True, help_text='Restricted Diet eg. Vegan.', max_length=50, verbose_name='Suitable for'),
        ),
    ]
