# Generated by Django 3.2 on 2022-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0022_website'),
        ('blogapp', '0024_auto_20220218_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='websites',
            field=models.ManyToManyField(blank=True, to='contactapp.Website'),
        ),
    ]
