# Generated by Django 3.2 on 2022-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20220202_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbusiness',
            name='cost',
        ),
        migrations.AddField(
            model_name='reviewbusiness',
            name='bus_type',
            field=models.CharField(blank=True, help_text='Be specific eg. Restaurant, Dentist. see schema.org sub-types', max_length=200, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='reviewbusiness',
            name='menu',
            field=models.URLField(blank=True, help_text='Link to menu for restaurants.', max_length=100, verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='reviewbusiness',
            name='price_range',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('CHEA', 'Cheap'), ('MODE', 'Moderate'), ('EXPE', 'Expensive')], help_text='How expensive?', max_length=4, verbose_name='Price Range'),
        ),
        migrations.AlterField(
            model_name='reviewbusiness',
            name='address_street',
            field=models.CharField(blank=True, default='default street', max_length=100, verbose_name='Street Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewbusiness',
            name='name',
            field=models.CharField(blank=True, default='default name', max_length=200, verbose_name='Business name'),
            preserve_default=False,
        ),
    ]
