# Generated by Django 3.2 on 2022-02-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_openinghours_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewBusiness',
            new_name='LocalBusiness',
        ),
    ]
