# Generated by Django 3.2 on 2022-02-03 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_rename_reviewbusiness_localbusiness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewBook',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='ReviewMovie',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='review_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='review_business',
            new_name='local_business',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='review_movie',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='localbusiness',
            name='endorsement',
        ),
        migrations.RemoveField(
            model_name='localbusiness',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='language',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='url_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='url_review',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.localbusiness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.localbusiness'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='bus_type',
            field=models.CharField(blank=True, help_text="Be specific eg. Restaurant, see schema.org 'types'", max_length=200, verbose_name='Business Type'),
        ),
    ]
