# Generated by Django 3.2 on 2022-02-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_auto_20220203_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.movie'),
            preserve_default=False,
        ),
    ]
