# Generated by Django 3.2 on 2022-02-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0030_auto_20220203_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='endorsement',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='url_review',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='endorsement',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url_review',
        ),
    ]
