# Generated by Django 3.2 on 2022-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_auto_20220203_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
