# Generated by Django 3.2 on 2022-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0034_auto_20220203_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbusiness',
            name='restaurant_cuisine',
            field=models.CharField(blank=True, help_text='Cuisine', max_length=100, verbose_name='Cuisine Offered.'),
        ),
        migrations.AddField(
            model_name='localbusiness',
            name='restaurant_type',
            field=models.CharField(blank=True, choices=[('CASU', 'Casual Dining'), ('FINE', 'Fine Dining'), ('FAST', 'Fast Service')], max_length=4, verbose_name='Restaurant Type'),
        ),
    ]
