# Generated by Django 3.2 on 2022-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0035_auto_20220203_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localbusiness',
            old_name='menu',
            new_name='restaurnt_menu',
        ),
        migrations.AddField(
            model_name='localbusiness',
            name='restaurant_reservations',
            field=models.BooleanField(default=False, help_text='Does the restaurant accept reservations?', verbose_name='Accepts Reservations'),
        ),
    ]
