# Generated by Django 3.2 on 2022-02-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0036_auto_20220203_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localbusiness',
            old_name='restaurnt_menu',
            new_name='restaurant_menu',
        ),
    ]
