# Generated by Django 3.2 on 2022-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0037_rename_restaurnt_menu_localbusiness_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutr_calories',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Number of calories per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_carbs',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of carbohydrates per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_choles',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Milligrams of cholesterol per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_fat',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of fat per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_fiber',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of fiber per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_protein',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of protein per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_sat_fat',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of staurated fat per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_sodium',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Milligrams of sodium per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_sugar',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of sugar per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_trans_fat',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of trans fat per serving.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutr_unsat_fat',
            field=models.CharField(blank=True, default=1, help_text='100', max_length=10, verbose_name='Grams of unstaurated fat per serving.'),
            preserve_default=False,
        ),
    ]
