# Generated by Django 3.2 on 2022-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0038_auto_20220204_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='review_restaurant',
        ),
        migrations.DeleteModel(
            name='ReviewRestaurant',
        ),
    ]
