# Generated by Django 3.2 on 2022-02-05 12:32

from django.db import migrations, models
import utilities.utils_images


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0039_auto_20220204_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '02. Articles'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name_plural': '04. Docs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '01. Locations'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-is_featured', '-date_published')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['menu_order', 'name'], 'verbose_name_plural': '06. Tags'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blogapp_pos_status_6d0062_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_21',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_lg',
            field=models.CharField(blank=True, help_text='Automatic size: 1200px x 600px', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_featured',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200 x 600px', null=True, upload_to=utilities.utils_images.new_filename_blog_feat),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'date_published', 'post_type', 'is_featured'], name='blogapp_pos_status_c8ef71_idx'),
        ),
    ]
