# Generated by Django 3.2.3 on 2021-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Denotes if an item should be considered unlimited.'),
        ),
    ]
