# Generated by Django 3.2 on 2022-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    # operations = [
        # migrations.RemoveField(
            # model_name='digital',
            # name='user_char_tield',
        # ),
        # migrations.RemoveField(
            # model_name='digital',
            # name='user_int_field',
        # ),
        # migrations.AddField(
            # model_name='digital',
            # name='new_char_tield',
            # field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
            # model_name='digital',
            # name='new_int_field',
            # field=models.BigIntegerField(blank=True, null=True),
        # ),
    # ]
