# Generated by Django 3.2 on 2022-02-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='supplier',
        ),
    ]
