# Generated by Django 3.2 on 2022-02-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='attribute',
        ),
    ]
