# Generated by Django 3.2.3 on 2021-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_item_is_unlimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_unlimited',
        ),
        migrations.AddField(
            model_name='productpartjoin',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Denotes if an item should be considered unlimited.'),
        ),
    ]
