# Generated by Django 3.2 on 2022-02-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_remove_term_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsapp.group')),
                ('new_field', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': '07. Attributes',
            },
            bases=('itemsapp.group',),
        ),
        migrations.AlterField(
            model_name='Group',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.group'),
        ),
        migrations.AlterField(
            model_name='Item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_items', to='itemsapp.Department'),
        ),
        migrations.AlterField(
            model_name='Item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_items', to='itemsapp.Category'),
        ),
        migrations.AlterField(
            model_name='Item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_item', to='itemsapp.Tag'),
        ),
    ]
