# Generated by Django 3.2 on 2022-04-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_auto_20220401_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digital',
        ),
    ]
