# Generated by Django 3.2 on 2022-02-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0003_auto_20220206_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
