# Generated by Django 3.2 on 2022-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0003_delete_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
