# Generated by Django 3.2.3 on 2021-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0003_auto_20210825_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartjoin',
            name='quantity',
            field=models.IntegerField(default=1, help_text='How many parts per product?'),
        ),
    ]
