# Generated by Django 3.2 on 2022-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_auto_20220225_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='For internal and purchasing use.', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='comma, separated, list', max_length=200)),
                ('cost', models.BigIntegerField(default=0)),
                ('cost_shipping', models.BigIntegerField(default=0)),
                ('cost_quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='For internal and purchasing use.', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='comma, separated, list', max_length=200)),
                ('cost', models.BigIntegerField(default=0)),
                ('cost_shipping', models.BigIntegerField(default=0)),
                ('cost_quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='For internal and purchasing use.', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='comma, separated, list', max_length=200)),
                ('cost', models.BigIntegerField(default=0)),
                ('cost_shipping', models.BigIntegerField(default=0)),
                ('cost_quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='itemsapp_pr_sku_1b57e7_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['sku'], name='itemsapp_pa_sku_6b062e_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['sku'], name='itemsapp_co_sku_9a979a_idx'),
        ),
    ]
