# Generated by Django 3.2.3 on 2021-09-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_alter_productpartjoin_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartjoin',
            name='use_all',
            field=models.BooleanField(default=False, help_text='Use all part inventory when the related product is brought into inventory.'),
        ),
        migrations.AlterField(
            model_name='productpartjoin',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Denotes if a part should be considered unlimited.'),
        ),
    ]
