# Generated by Django 3.2 on 2022-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0005_auto_20220225_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='categories',
            field=models.ManyToManyField(blank=True, to='itemsapp.Category'),
        ),
        migrations.AddField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(blank=True, to='itemsapp.Tag'),
        ),
        migrations.AddField(
            model_name='part',
            name='categories',
            field=models.ManyToManyField(blank=True, to='itemsapp.Category'),
        ),
        migrations.AddField(
            model_name='part',
            name='tags',
            field=models.ManyToManyField(blank=True, to='itemsapp.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='itemsapp.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='departments',
            field=models.ManyToManyField(blank=True, to='itemsapp.Department'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='itemsapp.Tag'),
        ),
    ]
