# Generated by Django 3.2.3 on 2021-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0005_auto_20210907_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ecpu_calc_from',
            field=models.CharField(blank=True, help_text='how ecpu has been calculated', max_length=100),
        ),
    ]
