# Generated by Django 3.2.3 on 2021-10-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0006_item_ecpu_calc_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name_plural': '03. Attributes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': '04. Categories'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name_plural': '01. Parts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '02. Products'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'tag', 'verbose_name_plural': '05. Tags'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='items',
        ),
    ]
