# Generated by Django 3.2 on 2022-02-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0006_attribute_new_field_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='new_field_two',
        ),
    ]
