# Generated by Django 3.2 on 2022-02-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0007_bid_identifier_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='How many parts are included in the cost of 1 product.')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollectionJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_min', models.IntegerField(default=0, help_text='Use to require minium order quantity.')),
                ('order_max', models.IntegerField(default=0, help_text='Use to limit order quantity.')),
                ('discount', models.IntegerField(default=0, help_text='Discount (5.0%) for purchase in collection.')),
                ('included_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incl_products_collection', to='itemsapp.product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_collection', to='itemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_variation', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('attributes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_productattributes', to='itemsapp.attribute')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_join_items', to='itemsapp.product')),
                ('terms', models.ManyToManyField(blank=True, related_name='term_productattributes', to='itemsapp.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='PartComponentJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='How many components are included in the cost of 1 part.')),
                ('components', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.component')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part')),
            ],
        ),
    ]
