# Generated by Django 3.2 on 2022-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0007_auto_20220206_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='new_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
