# Generated by Django 3.2.3 on 2021-10-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0008_auto_20211011_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.tag'),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.gender')),
            ],
            options={
                'verbose_name': 'gender',
                'verbose_name_plural': '04. Genders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.department')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': '04. Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='items', to='itemsapp.Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='items', to='itemsapp.Gender'),
        ),
    ]
