# Generated by Django 3.2 on 2022-02-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0008_partcomponentjoin_productattributejoin_productcollectionjoin_productpartjoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpartjoin',
            old_name='part',
            new_name='parts',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='itemsapp.ProductAttributeJoin', to='itemsapp.Attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_product_collections_+', through='itemsapp.ProductCollectionJoin', to='itemsapp.Product'),
        ),
    ]
