# Generated by Django 3.2 on 2022-02-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0008_attribute_new_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
