# Generated by Django 3.2 on 2022-02-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0009_auto_20220226_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='components',
            field=models.ManyToManyField(blank=True, through='itemsapp.PartComponentJoin', to='itemsapp.Component'),
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(blank=True, through='itemsapp.ProductPartJoin', to='itemsapp.Part'),
        ),
    ]
