# Generated by Django 3.2 on 2022-02-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0009_delete_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsapp.group')),
                ('new_field', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': '07. Attributes',
            },
            bases=('itemsapp.group',),
        ),
    ]
