# Generated by Django 3.2.3 on 2021-10-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0009_auto_20211011_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
