# Generated by Django 3.2 on 2022-02-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0010_auto_20220226_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unitinventory'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unitinventory'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_multiplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.costmultiplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. 100 if inventory = 120 cm, display = 1.2 meters'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unitdisplay'),
        ),
    ]
