# Generated by Django 3.2.3 on 2021-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0010_auto_20211011_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'verbose_name_plural': '04. Departments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.category',),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
            ],
            options={
                'verbose_name_plural': '04. Genders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.category',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'verbose_name_plural': '04. Tags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(blank=True, choices=[('CAT', 'Category'), ('TAG', 'Tag'), ('DEP', 'Department'), ('GEN', 'Gender')], max_length=3),
        ),
    ]
