# Generated by Django 3.2 on 2022-02-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0011_term_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalOption',
        ),
    ]
