# Generated by Django 3.2 on 2022-02-27 08:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0011_auto_20220226_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='part',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField()),
                ('begins', models.DateField(null=True)),
                ('ends', models.DateField(null=True)),
                ('percentage', models.BigIntegerField(blank=True, help_text='Percentage discount eg. 25% off', null=True)),
                ('fixed', models.BigIntegerField(blank=True, help_text='Fixed discount eg. $5.00 off', null=True)),
                ('price', models.BigIntegerField(blank=True, help_text='Fixed price eg. Sale Price $25.00', null=True)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('bogx', models.PositiveSmallIntegerField(help_text='Buy One Get x Free', null=True)),
                ('products', models.ManyToManyField(blank=True, to='itemsapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_sm', ckeditor.fields.RichTextField(blank=True, help_text='500 characters max.', max_length=500, null=True)),
                ('description_md', ckeditor.fields.RichTextField(blank=True, help_text='1000 characters max.', max_length=1000, null=True)),
                ('description_lg', ckeditor.fields.RichTextField(blank=True, help_text='1000 characters max.', max_length=1000, null=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_options', to='itemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_int_field', models.BigIntegerField(blank=True, null=True)),
                ('new_char_tield', models.CharField(blank=True, max_length=100)),
                ('part', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product')),
            ],
        ),
    ]
