# Generated by Django 3.2.3 on 2021-10-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
        ('itemsapp', '0011_auto_20211011_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_items', to='itemsapp.Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='gender_items', to='itemsapp.Gender'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_item', to='itemsapp.Tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_items', to='itemsapp.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='configapp.price'),
        ),
    ]
