# Generated by Django 3.2.3 on 2021-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0012_auto_20211011_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'category', 'verbose_name_plural': '05. Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '06. Tags'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='genders',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(blank=True, choices=[('CAT', 'Category'), ('TAG', 'Tag'), ('DEP', 'Department')], max_length=3),
        ),
    ]
