# Generated by Django 3.2 on 2022-02-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0012_delete_digitaloption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
