# Generated by Django 3.2 on 2022-02-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0013_delete_bundle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
