# Generated by Django 3.2.3 on 2021-10-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0013_auto_20211011_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
