# Generated by Django 3.2 on 2022-02-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='unit_inventory',
        ),
        migrations.RemoveField(
            model_name='component',
            name='unit_inventory',
        ),
        migrations.RemoveField(
            model_name='part',
            name='unit_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_display',
        ),
        migrations.DeleteModel(
            name='UnitDisplay',
        ),
        migrations.DeleteModel(
            name='UnitInventory',
        ),
    ]
