# Generated by Django 3.2.3 on 2021-10-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0014_auto_20211011_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(blank=True, choices=[('CAT', 'Category'), ('TAG', 'Tag'), ('DEP', 'Department')], max_length=3)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.group')),
            ],
            options={
                'ordering': ['parent__name', 'name'],
            },
        ),
    ]
