# Generated by Django 3.2 on 2022-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0014_auto_20220227_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('INV', 'Inventory Stock'), ('DIS', 'Display')], max_length=3)),
                ('singular', models.CharField(default='piece', max_length=100)),
                ('plural', models.CharField(default='pieces', max_length=100)),
            ],
        ),
    ]
