# Generated by Django 3.2 on 2022-02-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0014_delete_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_type',
        ),
        migrations.AddField(
            model_name='item',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.item'),
        ),
    ]
