# Generated by Django 3.2.3 on 2021-10-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0015_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name_plural': '05. Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.group',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'verbose_name_plural': '04. Departments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.group',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'verbose_name_plural': '06. Tags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.group',),
        ),
    ]
