# Generated by Django 3.2 on 2022-02-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0015_auto_20220206_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='test_field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='order_max',
            field=models.IntegerField(blank=True, default=0, help_text='Use to limit order quantity.'),
        ),
        migrations.AddField(
            model_name='item',
            name='order_min',
            field=models.IntegerField(blank=True, default=0, help_text='Use to require minium order quantity.'),
        ),
        migrations.AddField(
            model_name='item',
            name='use_parent_price',
            field=models.BooleanField(default=False, help_text='Used for collections.'),
        ),
        migrations.CreateModel(
            name='AttributeItemJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=200)),
                ('is_variation', models.BooleanField(default=False)),
                ('display_order', models.CharField(blank=True, max_length=20)),
                ('attribute', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.attribute')),
            ],
        ),
    ]
