# Generated by Django 3.2 on 2022-02-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0015_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unit'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unit'),
        ),
    ]
