# Generated by Django 3.2.3 on 2021-10-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0016_category_department_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name', 'children']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='parent',
            new_name='children',
        ),
    ]
