# Generated by Django 3.2 on 2022-02-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0016_auto_20220227_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='components',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='parts',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='products',
            new_name='product',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.component')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
