# Generated by Django 3.2 on 2022-02-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0017_auto_20220206_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsapp.item')),
                ('test_field', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': '02c. Digital Products',
            },
            bases=('itemsapp.item',),
        ),
    ]
