# Generated by Django 3.2 on 2022-02-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0017_auto_20220227_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unit'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product'),
        ),
        migrations.AlterField(
            model_name='costmultiplier',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.component'),
        ),
        migrations.AlterField(
            model_name='image',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.part'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_attribute_variations', to='itemsapp.attribute')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.product')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_term_variations', to='itemsapp.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.variation'),
        ),
    ]
