# Generated by Django 3.2.3 on 2021-10-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0017_auto_20211011_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='children',
            new_name='parent',
        ),
    ]
