# Generated by Django 3.2 on 2022-02-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0018_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.attribute'),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
