# Generated by Django 3.2 on 2022-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0019_auto_20220301_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. inventory_units=cm, display_units=meters then unit_base=100'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. inventory_units=cm, display_units=meters then unit_base=100'),
        ),
    ]
