# Generated by Django 3.2 on 2022-02-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0019_auto_20220206_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='term',
            new_name='terms',
        ),
    ]
