# Generated by Django 3.2.3 on 2021-10-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0019_remove_group_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='itemsapp.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
