# Generated by Django 3.2.3 on 2021-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0020_groupchildren'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_items', to='itemsapp.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_items', to='itemsapp.Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_item', to='itemsapp.Tag'),
        ),
    ]
