# Generated by Django 3.2 on 2022-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0020_auto_20220301_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='plural',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='singular',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='unit',
            name='dis_plural',
            field=models.CharField(default='meters', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='dis_singular',
            field=models.CharField(default='meter', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='inv_plural',
            field=models.CharField(default='centimeters', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='inv_singular',
            field=models.CharField(default='centimeter', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. 100 if inventory = 120 cm, display = 1.2 meters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. inventory_units=cm, display_units=meters then unit_base=100'),
        ),
    ]
