# Generated by Django 3.2 on 2022-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0020_rename_term_attribute_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalproduct',
            options={'verbose_name_plural': '02b. Digital Products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '02a. Products'},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='default-slug'),
            preserve_default=False,
        ),
    ]
