# Generated by Django 3.2.3 on 2021-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0021_auto_20211011_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(blank=True, choices=[('SIMP', 'Simple'), ('DIGI', 'Digital'), ('BUND', 'Bundled'), ('VARI', 'Variable')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('PART', 'Part'), ('PROD', 'Product')], max_length=4),
        ),
        migrations.DeleteModel(
            name='GroupChildren',
        ),
    ]
