# Generated by Django 3.2 on 2022-02-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0021_auto_20220206_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_class',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_base',
            field=models.IntegerField(default=1, help_text='eg. 100 if inventory = 120 cm, display = 1.2 meters'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_plural',
            field=models.CharField(blank=True, help_text='plural unit eg. pieces', max_length=40),
        ),
        migrations.AddField(
            model_name='item',
            name='use_calculated_price',
            field=models.BooleanField(default=False, help_text='Use price calculated from costs.'),
        ),
        migrations.AddField(
            model_name='item',
            name='use_calculated_quantity',
            field=models.BooleanField(default=False, help_text='Use quantity calculated from stock.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='itemsapp.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='departments', to='itemsapp.Department'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='itemsapp.Tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, help_text='singlular unit eg. piece', max_length=40),
        ),
    ]
