# Generated by Django 3.2 on 2022-03-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0021_auto_20220301_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='unit_inventory',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='unit_inventory',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_display',
            new_name='unit',
        ),
    ]
