# Generated by Django 3.2.3 on 2021-10-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0022_auto_20211012_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleProduct',
            fields=[
            ],
            options={
                'verbose_name_plural': '02d. Bundle Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.item',),
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
            ],
            options={
                'verbose_name_plural': '02c. Digital Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.item',),
        ),
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
            ],
            options={
                'verbose_name_plural': '02b. Simple Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.item',),
        ),
        migrations.CreateModel(
            name='VariableProduct',
            fields=[
            ],
            options={
                'verbose_name_plural': '02e. Varialbe Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.item',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '02a. All Products'},
        ),
    ]
