# Generated by Django 3.2 on 2022-02-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0022_auto_20220206_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
