# Generated by Django 3.2 on 2022-03-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0023_auto_20220301_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='variation',
        ),
    ]
