# Generated by Django 3.2 on 2022-03-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0024_remove_image_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='ProductVariationJoin',
        ),
    ]
