# Generated by Django 3.2 on 2022-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0024_auto_20220207_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, help_text='comma, separated, list', max_length=200),
        ),
    ]
