# Generated by Django 3.2.3 on 2021-12-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0025_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='For internal and purchasing use.'),
        ),
    ]
