# Generated by Django 3.2 on 2022-02-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0025_item_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='attributeitemjoin',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
