# Generated by Django 3.2 on 2022-03-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0026_auto_20220301_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariationjoin',
            name='attribute',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_pvj', to='itemsapp.attribute'),
        ),
        migrations.AlterField(
            model_name='productvariationjoin',
            name='variations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_pvj', to='itemsapp.product'),
        ),
    ]
