# Generated by Django 3.2 on 2022-03-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0028_rename_variations_productvariationjoin_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributejoin',
            old_name='attributes',
            new_name='attribute',
        ),
    ]
