# Generated by Django 3.2 on 2022-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0028_auto_20220210_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='item_categories', to='itemsapp.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='item_departments', to='itemsapp.Department'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='item_tags', to='itemsapp.Tag'),
        ),
    ]
