# Generated by Django 3.2 on 2022-03-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0029_rename_attributes_productattributejoin_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='unit_inventory',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='component',
            name='unit_base',
        ),
        migrations.RemoveField(
            model_name='part',
            name='unit_base',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_base',
        ),
    ]
