# Generated by Django 3.2 on 2022-02-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0009_auto_20220210_2239'),
        ('blogapp', '0008_auto_20220210_1131'),
        ('itemsapp', '0029_auto_20220210_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
