# Generated by Django 3.2 on 2022-02-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0009_auto_20220210_2239'),
        ('itemsapp', '0030_delete_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
            ],
            options={
                'verbose_name_plural': '07. Attributes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
    ]
