# Generated by Django 3.2 on 2022-03-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0030_auto_20220301_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='supplier',
        ),
    ]
