# Generated by Django 3.2 on 2022-02-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0031_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='use_parent_price',
        ),
        migrations.AddField(
            model_name='item',
            name='calculated_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='calculated_stock_quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='collection_quantity',
            field=models.IntegerField(blank=True, help_text='How many items are included in the collection.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='use_subitem_sum',
            field=models.BooleanField(default=False, help_text='Price is the summation of subitems.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_max',
            field=models.IntegerField(blank=True, help_text='Use to limit order quantity.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_min',
            field=models.IntegerField(blank=True, help_text='Use to require minium order quantity.', null=True),
        ),
    ]
