# Generated by Django 3.2 on 2022-02-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0033_auto_20220211_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier_type', models.CharField(blank=True, choices=[('FL', 'Flat Rate'), ('GM', 'Gross Margin'), ('MU', 'Markup')], max_length=4)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'ordering': ['multiplier_type', 'amount'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
