# Generated by Django 3.2 on 2022-03-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0013_auto_20220302_1249'),
        ('itemsapp', '0033_auto_20220302_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Digital',
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PartComponentJoin',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttributeJoin',
        ),
        migrations.DeleteModel(
            name='ProductCollectionJoin',
        ),
        migrations.DeleteModel(
            name='ProductPartJoin',
        ),
        migrations.DeleteModel(
            name='ProductVariationJoin',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
