# Generated by Django 3.2 on 2022-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0034_auto_20220302_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='For internal and purchasing use.', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='comma, separated, list', max_length=200)),
                ('cost', models.BigIntegerField(default=0)),
                ('cost_shipping', models.BigIntegerField(default=0)),
                ('cost_quantity', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='itemsapp_it_sku_27a3ad_idx'),
        ),
    ]
