# Generated by Django 3.2 on 2022-02-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0035_rename_price_costmultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_multiplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.costmultiplier'),
        ),
    ]
