# Generated by Django 3.2 on 2022-03-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0037_auto_20220302_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('COMP', 'Component'), ('PART', 'Part'), ('PROD', 'Product')], default='COMP', max_length=4),
            preserve_default=False,
        ),
    ]
