# Generated by Django 3.2 on 2022-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0038_auto_20220211_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-f4118f96-a1e3-4069-a169', max_length=100, unique=True),
        ),
    ]
