# Generated by Django 3.2 on 2022-03-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0038_auto_20220302_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCollectionJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_min', models.IntegerField(default=0, help_text='Use to require minium order quantity.')),
                ('order_max', models.IntegerField(default=0, help_text='Use to limit order quantity.')),
                ('discount', models.IntegerField(default=0, help_text='Discount (5.0%) for purchase in collection.')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='assembly',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_assembly_+', through='itemsapp.ItemAssemblyJoin', to='itemsapp.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='itemsapp.ItemAttributeJoin', to='itemsapp.Attribute'),
        ),
        migrations.AddField(
            model_name='item',
            name='brands',
            field=models.ManyToManyField(blank=True, to='itemsapp.Brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_multiplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.costmultiplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, to='itemsapp.Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_variations_+', through='itemsapp.ItemVariationJoin', to='itemsapp.Item'),
        ),
        migrations.DeleteModel(
            name='ProductCollectionJoin',
        ),
        migrations.AddField(
            model_name='itemcollectionjoin',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coll_coll_join', to='itemsapp.item'),
        ),
        migrations.AddField(
            model_name='itemcollectionjoin',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_coll_join', to='itemsapp.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_collections_+', through='itemsapp.ItemCollectionJoin', to='itemsapp.Item'),
        ),
    ]
