# Generated by Django 3.2 on 2022-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0039_auto_20220302_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
