# Generated by Django 3.2 on 2022-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0039_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-fa422f57-e45e-4eb8-9a1c', max_length=100, unique=True),
        ),
    ]
