# Generated by Django 3.2 on 2022-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0040_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-99495c1a-d5b2-417b-a7ff', max_length=100, unique=True),
        ),
    ]
