# Generated by Django 3.2 on 2022-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0040_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ecpu',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='ecpu_from',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
