# Generated by Django 3.2 on 2022-03-04 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0023_auto_20220302_1138'),
        ('itemsapp', '0041_auto_20220303_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(choices=[('APAY', 'Accounts Payable'), ('COGM', 'Cost of Goods Manufactured'), ('COGS', 'Cost of Goods Sold'), ('CASH', 'Cash Account'), ('IRAW', 'Inventory Raw Materials'), ('IMER', 'Inventory Merchandise'), ('ILOS', 'Inventory Loss'), ('OWEQ', 'Owner Equity')], max_length=4)),
                ('date', models.DateField(default=datetime.date.today)),
                ('lot', models.DateTimeField(default=django.utils.timezone.now)),
                ('debit_quantity', models.BigIntegerField(blank=True, null=True)),
                ('debit_amount', models.BigIntegerField(blank=True, null=True)),
                ('credit_quantity', models.BigIntegerField(blank=True, null=True)),
                ('credit_amount', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactapp.location')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
