# Generated by Django 3.2 on 2022-02-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
        ('itemsapp', '0041_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-ff4b87f4-5acd-4241-9225', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, help_text='Divides by this number. 1 box if used by box, or 24 pcs per box if used by piece', null=True)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('parts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_parts', to='itemsapp.part')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_products', to='itemsapp.product')),
                ('suppliers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactapp.supplier')),
            ],
        ),
    ]
