# Generated by Django 3.2 on 2022-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0042_auto_20220212_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost_other',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-82c6eefe-5783-411c-8843', max_length=100, unique=True),
        ),
    ]
