# Generated by Django 3.2 on 2022-02-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0046_auto_20220212_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='units',
        ),
        migrations.AddField(
            model_name='bid',
            name='unit_inventory',
            field=models.ManyToManyField(blank=True, to='itemsapp.UnitInventory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-a80dd22f-88ff-473f-86f5', max_length=100, unique=True),
        ),
    ]
