# Generated by Django 3.2 on 2022-02-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0047_auto_20220212_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='unit_inventory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_display',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_inventory',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-debf5a2e-67e3-4a63-9bbb', max_length=100, unique=True),
        ),
    ]
