# Generated by Django 3.2 on 2022-02-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0048_auto_20220212_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsapp.unitinventory'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_display', to='itemsapp.unitdisplay'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_inventory', to='itemsapp.unitinventory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-3f4af92b-cc72-4336-8c24', max_length=100, unique=True),
        ),
    ]
