# Generated by Django 3.2 on 2022-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0049_auto_20220212_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='parts',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='suppliers',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-6e8bcafe-a13b-4746-92b1', max_length=100, unique=True),
        ),
    ]
