# Generated by Django 3.2 on 2022-02-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0050_auto_20220212_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, help_text='For internal and purchasing use.', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-a8b96c80-1f11-4331-b860', max_length=100, unique=True),
        ),
    ]
