# Generated by Django 3.2 on 2022-02-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0052_auto_20220212_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-c76b9b7f-6b8f-426a-b7fc', max_length=100, unique=True),
        ),
    ]
