# Generated by Django 3.2 on 2022-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0054_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-9e439b76-33cb-4a18-b247', max_length=100, unique=True),
        ),
    ]
