# Generated by Django 3.2 on 2022-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0057_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-07750d44-a223-43bd-8e05', max_length=100, unique=True),
        ),
    ]
