# Generated by Django 3.2 on 2022-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0058_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-e1268a4e-8c4a-4a64-b560', max_length=100, unique=True),
        ),
    ]
