# Generated by Django 3.2 on 2022-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0059_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-d96be5c1-25ef-407e-9efa', max_length=100, unique=True),
        ),
    ]
