# Generated by Django 3.2 on 2022-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0060_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-07baffe2-22ad-4a07-8a43', max_length=100, unique=True),
        ),
    ]
