# Generated by Django 3.2 on 2022-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0062_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-402c49a1-67b3-491a-a337', max_length=100, unique=True),
        ),
    ]
