# Generated by Django 3.2 on 2022-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0063_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-84b4dec4-4393-4e66-85a2', max_length=100, unique=True),
        ),
    ]
