# Generated by Django 3.2 on 2022-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0064_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-f5c143c6-b95c-4c9b-bad1', max_length=100, unique=True),
        ),
    ]
