# Generated by Django 3.2 on 2022-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0065_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-b40f8b6b-a27b-4ff8-b825', max_length=100, unique=True),
        ),
    ]
