# Generated by Django 3.2 on 2022-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0069_auto_20220213_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-980b85d1-2ead-4a62-adc2', max_length=100, unique=True),
        ),
    ]
