# Generated by Django 3.2 on 2022-02-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0071_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-fd212515-5208-4810-8667', max_length=100, unique=True),
        ),
    ]
