# Generated by Django 3.2 on 2022-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0073_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-45168b56-afd2-4934-a45f', max_length=100, unique=True),
        ),
    ]
