# Generated by Django 3.2 on 2022-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0076_auto_20220214_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_collections_+', to='itemsapp.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='components_quantity',
            field=models.IntegerField(blank=True, help_text='How many items are included in the collection.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-ae47e5b8-20a8-41ea-a9a8', max_length=100, unique=True),
        ),
    ]
