# Generated by Django 3.2 on 2022-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0077_auto_20220214_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='item',
            name='components_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='component_quantity',
            field=models.IntegerField(blank=True, help_text='How many components are included.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(blank=True, help_text='How many items are included.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_items_+', to='itemsapp.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-90c6cb10-d003-48eb-aac2', max_length=100, unique=True),
        ),
    ]
