# Generated by Django 3.2 on 2022-02-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0078_auto_20220214_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='component_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='components',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_max',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_min',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='itemsapp.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-8cc5c536-df67-442d-8a39', max_length=100, unique=True),
        ),
    ]
