# Generated by Django 3.2 on 2022-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0080_auto_20220214_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
            ],
            options={
                'verbose_name_plural': '01. Component',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('itemsapp.item',),
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name_plural': '02. Parts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '03. Products'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='component_parent',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('COMP', 'Component'), ('PART', 'Part'), ('PROD', 'Product')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-f315a259-e23b-45ba-84c7', max_length=100, unique=True),
        ),
    ]
