# Generated by Django 3.2 on 2022-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0081_auto_20220215_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_components_+', to='itemsapp.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-fab6c688-847c-44bc-90d9', max_length=100, unique=True),
        ),
    ]
