# Generated by Django 3.2 on 2022-02-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0083_auto_20220215_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_components', to='itemsapp.component'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-be312a76-54f0-41f3-9219', max_length=100, unique=True),
        ),
    ]
