# Generated by Django 3.2 on 2022-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0086_auto_20220215_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentjoin',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componentjoin',
            name='cost_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='componentjoin',
            name='cost_shipping',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_shipping',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-1938ff0a-209a-4397-a663', max_length=100, unique=True),
        ),
    ]
