# Generated by Django 3.2 on 2022-02-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0087_auto_20220215_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_components_+', through='itemsapp.ComponentJoin', to='itemsapp.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-c4d930a2-a3b8-4148-afea', max_length=100, unique=True),
        ),
    ]
