# Generated by Django 3.2 on 2022-02-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0088_auto_20220215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentjoin',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_components', to='itemsapp.component'),
        ),
        migrations.AddField(
            model_name='componentjoin',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_parts', to='itemsapp.part'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-9aadf748-b77c-4080-b477', max_length=100, unique=True),
        ),
    ]
