# Generated by Django 3.2 on 2022-02-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0089_auto_20220215_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentjoin',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentjoin',
            name='part',
        ),
        migrations.AddField(
            model_name='componentjoin',
            name='from_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_item', to='itemsapp.part'),
        ),
        migrations.AddField(
            model_name='componentjoin',
            name='to_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_item', to='itemsapp.component'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-046dab7c-655d-48c5-aa12', max_length=100, unique=True),
        ),
    ]
