# Generated by Django 3.2 on 2022-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0090_auto_20220215_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='components',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-f1e80df3-dde2-4aed-94dc', max_length=100, unique=True),
        ),
    ]
