# Generated by Django 3.2 on 2022-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0091_auto_20220215_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_components_+', through='itemsapp.ComponentJoin', to='itemsapp.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-6d6b0ffe-48a4-4cc6-aeca', max_length=100, unique=True),
        ),
    ]
