# Generated by Django 3.2 on 2022-02-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0092_auto_20220215_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentjoin',
            name='from_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_item', to='itemsapp.item'),
        ),
        migrations.AlterField(
            model_name='componentjoin',
            name='to_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_item', to='itemsapp.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-6100aed8-39db-4878-95e3', max_length=100, unique=True),
        ),
    ]
