# Generated by Django 3.2 on 2022-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0093_auto_20220215_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentjoin',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='componentjoin',
            name='cost_quantity',
        ),
        migrations.RemoveField(
            model_name='componentjoin',
            name='cost_shipping',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='SKU-25694aaf-9c6c-4b3f-a2df', max_length=100, unique=True),
        ),
    ]
