# Generated by Django 3.2 on 2022-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0097_delete_productpartjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='attribute_items', to='itemsapp.AttributeItemJoin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_items', to='itemsapp.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_items', to='itemsapp.Department'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_items', to='itemsapp.Tag'),
        ),
    ]
