# Generated by Django 3.2 on 2022-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0029_alter_group_options'),
        ('itemsapp', '0098_auto_20220218_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='ItemDepartment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AlterModelOptions(
            name='digitalproduct',
            options={'verbose_name_plural': 'Digital Products'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_items', to='itemsapp.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_items', to='itemsapp.ItemDepartment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_items', to='itemsapp.ItemTag'),
        ),
    ]
