# Generated by Django 3.2 on 2022-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0099_auto_20220220_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
