# Generated by Django 3.2 on 2022-02-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0101_auto_20220220_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_max',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_min',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_parent',
        ),
    ]
