# Generated by Django 3.2 on 2022-02-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0102_auto_20220221_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentjoin',
            name='from_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components_from_item', to='itemsapp.item'),
        ),
        migrations.AlterField(
            model_name='componentjoin',
            name='to_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components_to_item', to='itemsapp.item'),
        ),
    ]
