# Generated by Django 3.2 on 2022-02-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0103_auto_20220221_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='How many items are included in the collection.')),
                ('order_min', models.IntegerField(default=0, help_text='Use to require minium order quantity.')),
                ('order_max', models.IntegerField(default=0, help_text='Use to limit order quantity.')),
                ('from_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_from_item', to='itemsapp.item')),
                ('to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_to_item', to='itemsapp.item')),
            ],
        ),
    ]
