# Generated by Django 3.2 on 2022-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0104_collectionjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_item_collections_+', through='itemsapp.CollectionJoin', to='itemsapp.Item'),
        ),
    ]
