# Generated by Django 3.2 on 2022-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0105_item_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='AttributeItemJoin',
        ),
    ]
