# Generated by Django 3.2 on 2022-02-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0106_auto_20220221_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_variation', models.BooleanField(default=False)),
                ('display_order', models.CharField(blank=True, max_length=20)),
                ('from_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes_from_item', to='itemsapp.item')),
                ('to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes_to_item', to='itemsapp.item')),
            ],
        ),
    ]
