# Generated by Django 3.2 on 2022-02-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0107_attributejoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributejoin',
            name='to_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes_to_item', to='itemsapp.itemattribute'),
        ),
    ]
