# Generated by Django 3.2 on 2022-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0110_auto_20220221_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributejoin',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='_itemsapp_attributejoin_terms_+', through='itemsapp.AttributeJoin', to='itemsapp.AttributeJoin'),
        ),
    ]
