# Generated by Django 3.2 on 2022-02-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0111_attributejoin_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributejoin',
            name='terms',
        ),
    ]
