# Generated by Django 3.2 on 2022-02-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0113_attributejoin_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
    ]
