# Generated by Django 3.2 on 2022-02-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0114_remove_item_attributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeJoin',
        ),
    ]
