# Generated by Django 3.2 on 2022-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0116_attributejoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='itemsapp.AttributeJoin', to='itemsapp.ItemAttribute'),
        ),
    ]
