# Generated by Django 3.2 on 2022-02-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0119_attributejoin_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionjoin',
            name='quantity',
        ),
    ]
