# Generated by Django 3.2 on 2022-02-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0120_remove_collectionjoin_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionjoin',
            old_name='to_item',
            new_name='included_items',
        ),
    ]
