# Generated by Django 3.2 on 2022-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0121_rename_to_item_collectionjoin_included_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
    ]
