# Generated by Django 3.2 on 2022-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0125_item_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjoin',
            name='discount',
            field=models.IntegerField(default=1, help_text='Discount (5.0%) for purchase in collection.'),
        ),
    ]
