# Generated by Django 3.2 on 2022-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0126_collectionjoin_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionjoin',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount (5.0%) for purchase in collection.'),
        ),
    ]
