# Generated by Django 3.2 on 2022-02-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0127_alter_collectionjoin_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
    ]
