# Generated by Django 3.2 on 2022-02-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0128_remove_item_collections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionJoin',
        ),
    ]
