# Generated by Django 3.2 on 2022-02-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_auto_20220225_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address_01', models.CharField(blank=True, max_length=200)),
                ('address_02', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('ship_address_01', models.CharField(blank=True, max_length=200)),
                ('ship_address_02', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(blank=True, max_length=200)),
                ('ship_state', models.CharField(blank=True, max_length=200)),
                ('ship_zipcode', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address_01', models.CharField(blank=True, max_length=200)),
                ('address_02', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('ship_address_01', models.CharField(blank=True, max_length=200)),
                ('ship_address_02', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(blank=True, max_length=200)),
                ('ship_state', models.CharField(blank=True, max_length=200)),
                ('ship_zipcode', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domain eg. example.com')),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address_01', models.CharField(blank=True, max_length=200)),
                ('address_02', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('ship_address_01', models.CharField(blank=True, max_length=200)),
                ('ship_address_02', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(blank=True, max_length=200)),
                ('ship_state', models.CharField(blank=True, max_length=200)),
                ('ship_zipcode', models.CharField(blank=True, max_length=200)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactapp.customer')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
