# Generated by Django 3.2 on 2022-02-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsapp', '0005_auto_20220213_1004'),
        ('blogapp', '0010_alter_post_locations'),
        ('configapp', '0013_alter_group_locations'),
        ('ledgerapp', '0005_auto_20220213_1004'),
        ('contactapp', '0004_auto_20220213_1004'),
        ('itemsapp', '0056_alter_item_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contactapp.location',),
        ),
    ]
