# Generated by Django 3.2 on 2022-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20220213_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contactapp.person',),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ManyToManyField(blank=True, to='contactapp.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('COMP', 'Company'), ('SUPP', 'Supplier'), ('STOR', 'Store'), ('WARE', 'Warehouse'), ('WEBS', 'Website')], max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('CUST', 'Customer'), ('CONT', 'Contact')], max_length=4),
        ),
    ]
