# Generated by Django 3.2 on 2022-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0010_alter_profile_cdn_dir'),
        ('contactapp', '0006_auto_20220225_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='configapp.Supplier'),
        ),
    ]
