# Generated by Django 3.2 on 2022-02-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_auto_20220217_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'l. Company', 'verbose_name_plural': 'l. Companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'c. Contact', 'verbose_name_plural': 'c. Contact'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'c. Customer', 'verbose_name_plural': 'c. Customers'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'l. Store', 'verbose_name_plural': 'l. Stores'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'l. Supplier', 'verbose_name_plural': 'l. Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'l. Warehouse', 'verbose_name_plural': 'l. Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['name'], 'verbose_name': 'l. Website', 'verbose_name_plural': 'l. Websites'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='ship_zipcode',
        ),
    ]
