# Generated by Django 3.2 on 2022-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0007_contact_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(blank=True, to='contactapp.Category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contactapp.Tag'),
        ),
        migrations.AddField(
            model_name='customer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='contactapp.Category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contactapp.Tag'),
        ),
    ]
