# Generated by Django 3.2 on 2022-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0008_auto_20220225_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
