# Generated by Django 3.2 on 2022-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0008_location_ship_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='shop_zipcode',
            new_name='ship_zipcode',
        ),
    ]
