# Generated by Django 3.2 on 2022-03-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0009_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug']},
        ),
    ]
