# Generated by Django 3.2 on 2022-03-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0010_auto_20220301_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
    ]
