# Generated by Django 3.2 on 2022-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0010_auto_20220217_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ManyToManyField(blank=True, to='contactapp.Location'),
        ),
    ]
