# Generated by Django 3.2 on 2022-02-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0012_auto_20220217_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='contactapp.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='contactapp.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='contactapp.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='warehouses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='contactapp.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='websites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='contactapp.location'),
        ),
    ]
