# Generated by Django 3.2 on 2022-03-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0065_auto_20220302_0911'),
        ('contactapp', '0013_auto_20220302_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactapp.customer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='contact_stores', to='configapp.Store'),
        ),
        migrations.AddField(
            model_name='contact',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='contact_suppliers', to='configapp.Supplier'),
        ),
        migrations.AddField(
            model_name='contact',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='contact_warehouses', to='configapp.Warehouse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='contact_websites', to='configapp.Website'),
        ),
    ]
