# Generated by Django 3.2 on 2022-03-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0014_auto_20220302_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='warehouses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='websites',
        ),
    ]
