# Generated by Django 3.2 on 2022-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0014_auto_20220217_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contactapp.Location'),
        ),
        migrations.AddField(
            model_name='person',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='stores', to='contactapp.Location'),
        ),
        migrations.AddField(
            model_name='person',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='contactapp.Location'),
        ),
        migrations.AddField(
            model_name='person',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='contactapp.Location'),
        ),
        migrations.AddField(
            model_name='person',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='websites', to='contactapp.Location'),
        ),
    ]
