# Generated by Django 3.2 on 2022-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0022_auto_20220217_1912'),
        ('contactapp', '0015_auto_20220217_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='location_categories', to='contactapp.LocationCategory'),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='location_tags', to='contactapp.LocationTag'),
        ),
    ]
