# Generated by Django 3.2 on 2022-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0072_alter_profile_cdn_dir'),
        ('contactapp', '0015_auto_20220302_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
        migrations.AddField(
            model_name='contact',
            name='locations',
            field=models.ManyToManyField(blank=True, to='configapp.Location'),
        ),
    ]
