# Generated by Django 3.2 on 2022-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0016_auto_20220302_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
