# Generated by Django 3.2 on 2022-02-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0024_alter_group_group_type'),
        ('contactapp', '0017_auto_20220217_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('configapp.group',),
        ),
    ]
