# Generated by Django 3.2 on 2022-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0074_alter_profile_cdn_dir'),
        ('contactapp', '0017_auto_20220302_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address_01', models.CharField(blank=True, max_length=200)),
                ('address_02', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('ship_address_01', models.CharField(blank=True, max_length=200)),
                ('ship_address_02', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(blank=True, max_length=200)),
                ('ship_state', models.CharField(blank=True, max_length=200)),
                ('ship_zipcode', models.CharField(blank=True, max_length=200)),
                ('categories', models.ManyToManyField(blank=True, to='contactapp.Category')),
                ('locations', models.ManyToManyField(blank=True, to='configapp.Location')),
                ('tags', models.ManyToManyField(blank=True, to='contactapp.Tag')),
            ],
        ),
    ]
