# Generated by Django 3.2 on 2022-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0018_personcategory_persontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='person_categories', to='contactapp.PersonCategory'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='person_tags', to='contactapp.PersonTag'),
        ),
    ]
