# Generated by Django 3.2 on 2022-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0019_contact_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('CUST', 'Customer'), ('CONT', 'Contact')], max_length=4),
        ),
    ]
