# Generated by Django 3.2 on 2022-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0019_auto_20220217_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_locations', to='contactapp.LocationCategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_locations', to='contactapp.LocationTag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_people', to='contactapp.PersonCategory'),
        ),
        migrations.AlterField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_people', to='contactapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='store_people', to='contactapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='supplier_people', to='contactapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_people', to='contactapp.PersonTag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='warehouse_people', to='contactapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='website_people', to='contactapp.Location'),
        ),
    ]
