# Generated by Django 3.2 on 2022-02-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0020_auto_20220218_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
