# Generated by Django 3.2 on 2022-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0021_company_location_store_supplier_warehouse_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(blank=True, to='contactapp.Location'),
        ),
    ]
