# Generated by Django 3.2 on 2022-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0021_delete_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contactapp.location',),
        ),
    ]
